import React from 'react'
import Head from 'next/head'
import LogoSection from './logoSection'
import TopHeader from '../topHeader'
import Navbar from '../navbar'
import Footer from '../footer'
import PropTypes from 'prop-types'
import data from '../../data/generalData';

function HomeLayout(props) {
    return (
        <div className="max-w-full box-border pt-14 flex flex-col mx-auto w-100vw overflow-x-hidden border min-h-screen">
            <Head>
                <title>{props.title || "Some title"}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
                <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"></link>
                <script src="https://unpkg.com/rive-js@0.7.16/dist/rive.min.js"></script>
            </Head>
            <TopHeader />
            <LogoSection />
            <Navbar pages={data.navbar} />
            {props.children}
            <Footer />
        </div>
    )
}

HomeLayout.propTypes = {
    title: PropTypes.string.isRequired,
}

export default HomeLayout

