import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image 
          src="/images/ElegantStoneLogo.svg"
          alt="elegant stone logo"
          width="200px"
          height="200px"
        /> 
        <h1 className={styles.title}>
          ElegantStone
        </h1>

        <p className={styles.description}>
          WebStranica je u izradi!!! <br/>
          Kon/tel: +(382)68/523-530<br/>
          email: elegantstone.ba@gmail.com
        </p>

        <div className={styles.grid}>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          
        </a>
      </footer>
    </div>
  )
}
